### ISSUE TITLE
local genome, RNAseq and protein files

### ISSUE THREAD

**Issue by xingwu2** [ncbi/egapx#18]
Hi,

I am trying out the egapx for a genome that is not hosted on NCBI. I have all the required inputs (genome fasta, RNAseq reads in fastq, and protein sequences in fasta from related species). I wonder does egapx work with local files? 

This is the error I got from the program. 

> ERROR ~ index is out of range 0..-1 (index = 0)
>  -- Check script '/home/xw364/bin/egapx/nf/./subworkflows/ncbi/./rnaseq_short/star_wnode/main.nf' at line: 83 or see '/gpfs/gibbs/pi/dellaporta/shenqi_CPT/genome_annotation/ncbi/hap2/hap2_ncbi/nextflow.log' file for more details

Attached is my yaml file. 

Xing

[Ca.yaml.txt](https://github.com/user-attachments/files/16199091/Ca.yaml.txt)

**Comment by xingwu2** [comment]
OK, I have found a way to bypass the error. The names of the RNAseq files have to follow this > /([A-Za-z0-9]+).{1,2}$/ according to the > bin/egapx/nf/./subworkflows/ncbi/./rnaseq_short/star_wnode/main.nf. That means there is no special character allowed in the file names and they **end** in .1 or .2.

**Comment by xingwu2** [comment]
Sorry that I encountered another issue with my local RNAseq read files. 

```ERROR ~ Error executing process > 'egapx:rnaseq_collapse:run_rnaseq_collapse (3)'

Caused by:
  Process `egapx:rnaseq_collapse:run_rnaseq_collapse (3)` terminated with an error exit status (3)```

```Command error:
  00398/018/0054/RE FDC3018E691B8D21 0301/0018 2024-07-12T23:14:36.877003 bse-2021-001.bsehpc.carnegiescience.edu UNK_CLIENT      UNK_SESSION              rnaseq_collapse request-stop  500 4.473060131 0 40
  00398/007/0051/R  FDC3018E691B8D21 0302/0009 2024-07-12T23:14:36.890048 bse-2021-001.bsehpc.carnegiescience.edu UNK_CLIENT      UNK_SESSION              rnaseq_collapse extra         num_skipped=359328
  00398/007/0051/R  FDC3018E691B8D21 0303/0010 2024-07-12T23:14:36.890279 bse-2021-001.bsehpc.carnegiescience.edu UNK_CLIENT      UNK_SESSION              rnaseq_collapse Error: RNASEQ(CException::eUnknown) "collapse_group.cpp", line 167: SMemberAlignment::SMemberAlignment() --- Failed to get redundant counts from SRA alignment
```

**Comment by pstrope** [comment]
Hi,
We're working on a new release which will be out in a couple weeks. That should take care of these issues. Thank you for reporting.

Pooja

**Comment by pstrope** [comment]
Hi @xingwu2, 
A new version is out. Please give it a try!
Pooja
