### ISSUE TITLE
Output GFF3 misses attributes

### ISSUE THREAD

**Issue by ZuyaoLiu** [ncbi/egapx#19]
Dear developers,

I succesfully run the piple with my own data. However, the output gff has some problem.

1. The gff is not sequential, making it hard to be used by other GFF tools.
2. In the gff file, there is no "Parent" in the attributes of all CDS, mRNA and transcript(exons have it). Thus, it's hard to figure out which mRNA belongs to which gene, and which CDS belongs to which mRNA, especially when the gff is not sequential.

Could you please add Parent in the attributes and fix the order of the output?

Or is there any tools that can deal with the current output?

Thank you.

**Comment by pstrope** [comment]
@ZuyaoLiu 
Thank you for your suggestions. A new version 0.2-alpha is out. Both your points are taken care of in the new output gff. Please give it a try.

Pooja

**Comment by ZuyaoLiu** [comment]
Hi Pooja,

It worked pretty well. Thank you for debugging.

Zuyao
