### ISSUE TITLE
New update fails example data ?

### ISSUE THREAD

**Issue by Artifice120** [ncbi/egapx#22]
I have ran the previous version with my own data as well as the example in the the past. After downloading the newer versino I recieve the following error.

```
Traceback (most recent call last):
  File "ui/egapx.py", line 810, in <module>
    sys.exit(main(sys.argv))
  File "ui/egapx.py", line 794, in main
    subprocess.run(nf_cmd, check=True, capture_output=(args.verbosity <= VERBOSITY_QUIET), text=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

I used these commands 
```
source /lustre/isaac/scratch/jtorre28/e-gapx/egapx/v-env/bin/activate

python3 ui/egapx.py ./examples/input_D_farinae_small.yaml -e singularity -w tmp-test -o example_out
```
nextflow version is  24.04.2.5914

**Comment by pstrope** [comment]
what's your python version?

**Comment by Artifice120** [comment]
3.9.10

**Comment by Artifice120** [comment]
Also reverted nextflow to version 23.10.1 and received the same error, if it helps.

**Comment by pstrope** [comment]
looks like you are using v3.6, from your error message
 `File "/usr/lib64/python3.6/subprocess.py"`

**Comment by Artifice120** [comment]
Thanks for the catch, 

I was using a prefix conda env for nextflow and a v-env for e-gapx and a slurm module for python since I don't have root access. 

Updated the python version in the conda environment to simplify things.

Seems to be running fine now.
