### ISSUE TITLE
Error using input_D_farinae_small_rnaseq.yaml (v0.2-alpha)

### ISSUE THREAD

**Issue by richard-burhans** [ncbi/egapx#25]
Running `python3 ui/egapx.py ./examples/input_D_farinae_small_rnaseq.yaml -e docker -o example_out` gives me the following result:

```
!!WARNING!!
This is an alpha release with limited features and organism scope to collect initial feedback on execution. Outputs are not yet complete and not intended for production use.

ERROR: Missing parameter: 'taxid'
```

**Comment by etvedte** [comment]
Hello, 

This is an outdated yaml file. `taxid:` is a required parameter:
https://github.com/ncbi/egapx?tab=readme-ov-file#input-data-format

You should test with `./examples/input_D_farinae_small.yaml`
https://github.com/ncbi/egapx?tab=readme-ov-file#input-example

Eric
