### ISSUE TITLE
Relocate requirements.txt

### ISSUE THREAD

**Issue by JAlvarezJarreta** [ncbi/egapx#26]
Hello, I was wondering if it would be possible to relocate the `requirements.txt` file currently located inside the `ui` folder to the root of the repository? Most tools and Python systems expect these type of files (e.g. `requirements.txt`, `pyproject.toml`) to be located at the root, and not having these file in that setup in this case is affecting our automatic environment creation system. Thank you very much in advance!

**Comment by victzh** [comment]
Out of curiosity, what automatic environment creation system do you use? We'll move the file in the next release certainly, it was there originally just to keep it along with the Python script - the rest of the code is NextFlow.

**Comment by JAlvarezJarreta** [comment]
Thank you very much!

To answer your question, we have an in-house system in Ensembl created around [venv](https://docs.python.org/3/library/venv.html) to put all the virtual environments in an advisable location inside our cluster, so these can be accessed/loaded/listed in a similar fashion to what [pyenv](https://github.com/pyenv/pyenv) does, but with a significantly smaller footprint (we centralise the common Python versions and libraries, so these are only installed once for all the users). The implementation of this system was based on the premise that all repositories with Python code will have their `pyproject.toml`, `setup.py` and `requirements*.txt` files in the root, as it is the standard. Thus the request.

**Comment by victzh** [comment]
Thanks!

**Comment by victzh** [comment]
Done in new
