### ISSUE TITLE
Question: partial annotation

### ISSUE THREAD

**Issue by Artifice120** [ncbi/egapx#27]
Afternoon,

I previously used your program to annotate an foxglove aphid. The gene predictions seem fine except that the mitochondria genes seemed to have been removed, since they were present in the original assembly and not in the annotations. 

Since I know which contig contains the mitochondria genome,  can I have e-gapx just annotate the one 'skipped' contig ?

**Comment by pstrope** [comment]
We do not currently annotate organelles.

**Comment by Artifice120** [comment]
Thanks, 

Good to know.

Its small enough to just blast and annotate manually.

Works great on the main foxglove aphid genome.

![image](https://github.com/user-attachments/assets/0dfbca92-e6d0-492a-8d74-047daa3d3977)
