### ISSUE TITLE
STAR alignment threads not set to maximum?

### ISSUE THREAD

**Issue by Andy-B-123** [ncbi/egapx#32]
Slightly related to the other issue on run time. 

I noticed that the STAR alignment step is taking up the majority of run time, which is not unexpected. But I think it's not running at full resources? I see that the run\_star step is set to request 31 CPUs as it's a 'huge' and 'long' job, but in the actual 'run\_params.yaml' the threads are set to 16? ('--runThreadN 16')?

Link to some of the run files here as a zip. I know I can adjust some of these parameters in the setup but wanted to check in if I'm missing something before things for individual steps!  Thanks!

![](https://github.com/user-attachments/assets/bd5c92f5-6664-4706-a226-38888704a417)

![](https://github.com/user-attachments/assets/be7c1917-c975-4446-b470-d770fab5167e)

![](https://github.com/user-attachments/assets/ee6871bc-9e68-4afd-8dfc-51351ad9a023)

https://drive.google.com/file/d/1HE-AaKZMUYRK2LRlcQwVtzGZUtLcmdRV/view?usp=drive_link

Bonus sneaky question - if I'm looking to run a plant (cactus actually) and if I provide oodles of RNA + protein data at run-time is there anything I should be wary of in the annotation? From the docs/description it looks like it's mostly that I'll be missing some of the background databases if I'm running an organism not currently supported?

**Comment by victzh** [comment]
Dear Andy,

Thanks for your interest in our products. You have a sharp eye, STAR threads allocation was suboptimal indeed. It should be fixed in the upcoming release in several weeks.

WRT cactus I will ask my colleagues.

**Comment by Xueliang24** [comment]
I am also waiting for good news about the threads used by STAR

**Comment by Andy-B-123** [comment]
It'd be nice (if possible) for the threads set for big job to automatically get applied there (eg for miniprot threads and STAR threads to be set to whatever value big job is set to). But if that kind of parameter is tricky to juggle in the workflow I don't mind changing it manually!  
  
Thanks again for your work on this. It was the first time I've had a NextFlow pipeline run out of the box, and it uses my institutions SLURM clusters, amazing to see.
