### ISSUE TITLE
multireader: command not found

### ISSUE THREAD

**Issue by fishman311** [ncbi/egapx#34]
Hi developers,

When I test example, my bash:

`pythion ../ui/egapx.py input_D_farinae_small.yaml -e singularity -w dfs_work -o dfs_out -lc ../local_cache`

The error is ：
ERROR ~ Error executing process > 'egapx:setup_proteins:convert_proteins'

Caused by:
  Process `egapx:setup_proteins:convert_proteins` terminated with an error exit status (127)

Command executed:

  mkdir -p asn
  mkdir -p fasta
  if [[ true == true ]]; then
      zcat src/6954.faa.gz | sed 's/>\([^ |]\+\)\( .*\)\?$/>lcl\|\1\2/' > fasta/6954.faa
  else
      sed 's/>\([^ |]\+\)\( .*\)\?$/>lcl\|\1\2/' src/6954.faa.gz > fasta/6954.faa
  fi
  multireader -flags ParseRawID -out-format asn_text -input fasta/6954.faa -output asn/6954.asn
  multireader -flags ParseRawID -out-format asn_binary -input fasta/6954.faa -output asn/6954.asnb

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 9: multireader: command not found

Work dir:
  /mnt/lfj/soft/egapx/test/dfs_work/75/9a8ad541a81803c75b1b85fe0d3ed3

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check 'dfs_out/nextflow.log' file for details

Could you help me solve this problem?

**Comment by pstrope** [comment]
Are you using a previous version of the pipeline or singularity container? We've seen something like this in a previous version.  Please remove the image completely, and then update the code and re-run.
