### ISSUE TITLE
Clarity on minimum memory requirement for run

### ISSUE THREAD

**Issue by Andy-B-123** [ncbi/egapx#4]
Hi, thank you for providing this, myself and my team are excited to implement this in our workflow!

I was just hoping to run the small example locally but I receive the following error following the example workflow provided with the "input\_D\_farinae\_small.yaml" dataset:

```
ERROR ~ Error executing process > 'egapx:annot_builder:annot_builder_main'

Caused by:
  Process requirement exceeds available memory -- req: 60 GB; avail: 7.6 GB
```

I know I am running this with low resources (WSL2 on Windows laptop) but I was mainly hoping to just get my head around the run before implementing this on our cluster. 

Could the requirement for minimum memory for a run be included in the example workflow to indicate to others that this requires certain memory resources? Or could a flag indicating max-memory be included, or a way of forcing a run through by the user if the expected actual memory requirement for the run is low?

Thank you!

**Comment by pstrope** [comment]
Hi, 
Thank you for trying out the software. At this moment we have not tested `egapx` to run on a laptop due to the heavy resources that it requires. However, we acknowledge the usefulness of being able to run it on a laptop for initial testing on the small example. There are config file values and task parameters that need to be changed for that to happen. We will look into this and provide you with instructions.

**Comment by victzh** [comment]
Are you comfortable with patching your copy of EGAPx source code? Also, do you use docker on WSL?
I have a version that fits in 4 CPUs, 6GB RAM and runs very limited subset just to demo the execution process.

You need to apply the patch to your code, [no-proteins.patch](https://github.com/ncbi/egapx/files/15166643/no-proteins.patch).
You also need to add the following code to the config file from egapx_config you use:
process {
    memory = 6.GB
    cpus = 4
}
Take the input file [input_D_farinae_minimal.txt](https://github.com/ncbi/egapx/files/15166699/input_D_farinae_minimal.txt) and run it through the system. On my (very fast) machine it takes around 9 minutes, so should be ready for you in reasonable time.

**Comment by Andy-B-123** [comment]
Amazing, thank you! Apologies for my late reply, this seems to be running for me now!
