### ISSUE TITLE
cross-species annotations

### ISSUE THREAD

**Issue by paulvhi** [ncbi/egapx#42]
We would like to run eGAPx to annotate a genome assembly using RNA-seq data from a different, but very closely related, species. We will not be able to obtain RNA from this species any time soon due to it's limited geographic distribution. 

Our first attempt was not very successful, with the number of genes predictecd in the species with RNA-seq data having ~16,300, while the "other closely related" species having only ~10,500. We used the protein set and RNA-seq data from different stages and tissues. 

Both species have very similar genomes and life history traits, thus we expect that both species have a similar number of protein coding genes. My manual annotations have ~92-98% pairwise identity (nucleotide) between orthologous odorant receptor genes (coding regions). 

Perhaps mapping is too stringent? Any suggestions how to improve these gene predictions using cross-species RNA-seq data?

**Comment by pstrope** [comment]
Hi, We will provide some instructions on modifying some default parameters in the next release.

**Comment by guo-cheng** [comment]
> Hi, We will provide some instructions on modifying some default parameters in the next release.

HI, Can I know the specific date in the next release.

**Comment by victzh** [comment]
The parameters for this are described in https://github.com/ncbi/egapx?tab=readme-ov-file#modifying-default-parameters, new release was just released today.
