### ISSUE TITLE
 Execution failed for '/scratch/...' No such file or directory

### ISSUE THREAD

**Issue by bbista** [ncbi/egapx#47]
Hello, 
I am having trouble with this particular process "egapx:rnaseq_short_plane:bam_strandedness:rnaseq_divide_by_strandedness".

I keep getting an error about a directory in scratch. 
I have also attached the slurm.config 
[slurm.config.txt](https://github.com/user-attachments/files/17652757/slurm.config.txt)
I think the issue is I do not see a scratch folder in my cluster but this process requires one. I could be wrong.

I have included the error message as well.
Any guidance is appreciated.

Best,
Bbista

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 3.

The full error message was:

Error executing process > 'egapx:rnaseq_short_plane:bam_strandedness:rnaseq_divide_by_strandedness'

Caused by:
  Process `egapx:rnaseq_short_plane:bam_strandedness:rnaseq_divide_by_strandedness` terminated with an error exit status (3)

Command executed:

  mkdir -p output
      samtools=$(which samtools)
      echo "GCA_020809275.1_ASM2080927v1_genomic-SRR8506572-Aligned.out.Sorted.bam
  GCA_020809275.1_ASM2080927v1_genomic-SRR9005248-Aligned.out.Sorted.bam" > bam_list.mft
      rnaseq_divide_by_strandedness -align-manifest bam_list.mft -metadata egapx_reads_metadata_mth5qzpx.tsv  -min-aligned 1000000 -min-unambiguous 200 -min-unambiguous-pct 2 -max-unambiguous-pct 100 -percentage-threshold 98  -samtools-executable $samtools -stranded-output output/stranded.list -strandedness-output output/run.strandedness -unstranded-output output/unstranded.list

Command exit status:
  3

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    Environment variable SINGULARITYENV_DISPLAY is set, but APPTAINERENV_DISPLAY is preferred
  INFO:    Environment variable SINGULARITYENV_SLURM_JOB_ID is set, but APPTAINERENV_SLURM_JOB_ID is preferred
  Error: (CFileErrnoException::eFileIO) mkstemp() failed for '/scratch/4220363/450285154624XXXXXX' (errno = 2: No such file or directory)
  Error: (106.16) Application's execution failed (CFileErrnoException::eFileIO) mkstemp() failed for '/scratch/4220363/450285154624XXXXXX' (errno = 2: No such file or directory)

Work dir:
  /project/meisel/users/bbista/Software/EgapX_scratch/fa/8a85df434abf145f8071bc958885ac

Container:
  /project/meisel/users/bbista/Software/egapx/project/meisel/users/bbista/Software/EgapX_scratch/scratch/ncbi-egapx-0.3.0-alpha.img

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by victzh** [comment]
There is a defect in one of our binaries which does not appear in our testing, and it hopefully can be avoided by modifying your config file. We'll fix it more permanently in subsequent release.

There are couple of problems I can see in the config.

First, for singularity.cacheDir it uses "project/meisel/users/..." and in the other couple places "/project/meisel/users/...". One is relative path, others are absolute - this can't be true at the same time, one of the paths is set wrong.

Second, you use scratch = null in the process settings. It is invalid value for scratch parameter and you probably need to use a valid directory for this, I'd suggest the same one used for SINGULARITY_TMPDIR. The second assignment of scratch = null in params section is extraneous and should be dropped.

Could you run it again with the modifications mentioned and report back, please?

**Comment by bbista** [comment]
Hello,
I was able to run the example succesfully. The issue it seems (I may not have the expertise to word it accurately) was that the main job was trying to access the scratch driectory of another job it sent out or vice versa. I do not know how scratch folder works in other clusters but the one I am running creates a /scratch/$SLURM_JOB_ID folder which is only accesible from within that job. 
I basically solved it by passing a bunch of parameters in the config file to designate one particular folder to be used for all scratch and temp driectory.  Attached is the slurm.config file that worked for me. I put it togther looking at nextflow configs for other clusters from the nextflow git. There may be redundant / invalid parameters in the config file.
`singularity {
    enabled = true
    autoMounts = true
    cacheDir = '/project/meisel/users/bbista/Software/egapx/scratch/' 
    envWhitelist='https_proxy,http_proxy,ftp_proxy,DISPLAY,SLURM_JOB_ID,SINGULARITY_BINDPATH,SINGULARITY_TMPDIR'
    runOptions = '-B /project/meisel/users/bbista/Software/egapx/scratch/'
    tmpDir ='/project/meisel/users/bbista/Software/egapx/scratch/' 
    temp ='/project/meisel/users/bbista/Software/egapx/scratch/' 
    runOptions : '-B /project/meisel/users/bbista/Software/egapx/scratch/ -B /project/meisel/users/bbista/Software/egapx/scratch/:/tmp/ -B /project/meisel/users/bbista/Software/egapx/scratch/:scratch'


}

env {
    SINGULARITY_CACHEDIR='/project/meisel/users/bbista/Software/EgapX_scratch/singularity/'
    TMP='/project/meisel/users/bbista/Software/egapx/scratch/' 
    TMPDIR='/project/meisel/users/bbista/Software/egapx/scratch/' 
    SINGULARITY_TMPDIR='/project/meisel/users/bbista/Software/egapx/scratch/' 
    SINGULARITY_LOCALCHACHEDIR='/project/meisel/users/bbista/Software/egapx/scratch/' 
    
}

process {
    resourceLimits = [
        memory: 120.GB,
        cpus: 16,
        time: 7.d
    ]
    executor = 'slurm'
    clusterOptions = "--mem-per-cpu=8GB"
    scratch = '/project/meisel/users/bbista/Software/egapx/scratch/' 
}

params {
    max_memory = 120.GB
    max_cpus = 16
    max_time = 7.d
}


`

Best,
B

**Comment by victzh** [comment]
Some of them are definitely redundant, e.g. singularity.tmpDir and env.SINGULARITY_TMPDIR (and probably env.TMP and env.TMPDIR), but it does not do any harm. Thanks for the report!
