### ISSUE TITLE
Could not find path for ortho taxid 7227

### ISSUE THREAD

**Issue by bismarck1008** [ncbi/egapx#49]
I used the new version [0.3.0-alpha](https://github.com/ncbi/egapx/releases/tag/v0.3.0-alpha)

python3 ui/egapx.py ./examples/input_D_farinae_small.yaml -e docker -w ./temp_datapath/D_farinae -o example_out

report error:
Could not find path for ortho taxid 7227

Is it a change in the database path or other issues

Thank you

**Comment by victzh** [comment]
Can you provide more details on the environment you use? What kind of HPC cluster, config file etc.?

**Comment by victzh** [comment]
We figured out some irregular behavior which appears only on some HPC clusters. If it worked for you at 0.2.0 release and stopped at 0.3.0 we're likely fixing it in coming bugfix 0.3.1 release.

**Comment by victzh** [comment]
Please try our new release 0.3.1-alpha

**Comment by victzh** [comment]
It was reported as fixed in another issue, I'm closing it.

**Comment by bismarck1008** [comment]
I'm sorry for the late reply due to network problems. I downloaded the latest version of the program, and the test data runs normally. Thank you very much
