### ISSUE TITLE
singularity image download

### ISSUE THREAD

**Issue by guo-cheng** [ncbi/egapx#50]
Hi,
Could you provide another way to get the egapx singularity image? It's hard to download image from the docker hub.

Guo-Cheng

**Comment by wq-ls** [comment]
在这个下面留言回复可能大都是国人，可以从这下载  https://cowtransfer.com/s/2642b1b3733049 点击链接查看 [ img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 p36re2 查看；

新建一个 NXF_SINGULARITY_CACHEDIR 目录，把镜像放进去，执行脚本前，
export NXF_SINGULARITY_CACHEDIR=/yourdir/egapx-0.3.0-alpha/NXF_SINGULARITY_CACHEDIR

**Comment by guo-cheng** [comment]
> p36re2
非常感谢！！！

**Comment by guo-cheng** [comment]
> 在这个下面留言回复可能大都是国人，可以从这下载 https://cowtransfer.com/s/2642b1b3733049 点击链接查看 [ img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 p36re2 查看；
> 
> 新建一个 NXF_SINGULARITY_CACHEDIR 目录，把镜像放进去，执行脚本前， export NXF_SINGULARITY_CACHEDIR=/yourdir/egapx-0.3.0-alpha/NXF_SINGULARITY_CACHEDIR

非常感谢！！！

**Comment by guo-cheng** [comment]
> 在重新上传个新的，一小时后，还在那个链接去下载看一下

好的，非常感谢！！！，那我关闭这个issue了。

**Comment by wq-ls** [comment]
更新： https://cowtransfer.com/s/4e493b236f0a43 点击链接查看 [ img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ecydn9 查看；

**Comment by guo-cheng** [comment]
> 更新： https://cowtransfer.com/s/4e493b236f0a43 点击链接查看 [ img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 ecydn9 查看；

感谢！
