### ISSUE TITLE
gene structure annotation

### ISSUE THREAD

**Issue by guo-cheng** [ncbi/egapx#51]
Hi,
I am using the egapx-0.3 to annotate an insect genome, i find some genes exon structure seems not right. Do you know how to improve this?

![test](https://github.com/user-attachments/assets/1069029e-768c-434e-9fd7-00767222b5a1)

**Comment by murphyte** [comment]
From your screenshot I can't say whether either of those models are correct, just that they're different from each other. Model quality is generally evidence-dependent. How much RNA-seq are you providing? How well does it cover this gene? We haven't yet set up the STAR alignment files to be included in the official output, but you can scan through all the working task directories for .bam files and try loading some of those to get a sense of how well this gene is represented. Protein alignments are also a factor, but those aren't in a form that you can easily review, and the RNA-seq is more important.

We're also planning to add some more logic that summarizes the evidence support for each model, but that'll be for a future version and require re-annotation.

**Comment by guo-cheng** [comment]
> From your screenshot I can't say whether either of those models are correct, just that they're different from each other. Model quality is generally evidence-dependent. How much RNA-seq are you providing? How well does it cover this gene? We haven't yet set up the STAR alignment files to be included in the official output, but you can scan through all the working task directories for .bam files and try loading some of those to get a sense of how well this gene is represented. Protein alignments are also a factor, but those aren't in a form that you can easily review, and the RNA-seq is more important.
> 
> We're also planning to add some more logic that summarizes the evidence support for each model, but that'll be for a future version and require re-annotation.
