### ISSUE TITLE
Crash when running 0.3.0-alpha

### ISSUE THREAD

**Issue by richard-burhans** [ncbi/egapx#55]
I'm getting a failure in `nf/subworkflows/ncbi/shared/diamond/main.nf`. I due to using `mkdir` instead of `mkdir -p`

**Comment by victzh** [comment]
Can you please provide us with the details of your configuration and command line. Also, an actual error file would be helpful. I don't think that blindly adding -p solves the actual problem, not just masks it. As we don't have this during our own test runs I would like to know the detailed circumstances of this error.

Thanks,

Victor.

**Comment by victzh** [comment]
The fix was applied to the original repo.
