### ISSUE TITLE
ERROR ~ Error executing process > 'egapx:setup_genome:get_genome_info'

### ISSUE THREAD

**Issue by dgpinheiro** [ncbi/egapx#58]
What is the command gc_create and where is it?

Command line executed: 
python3 ui/egapx.py ./examples/input_D_farinae_small.yaml -o example_out

Command error:
.command.sh: line 20: gc_create: command not found

**Comment by pstrope** [comment]
Hi,
What executor are you using (-e option)?

**Comment by dgpinheiro** [comment]
> Hi, What executor are you using (-e option)?

The default one, because I didn't set this parameter. I executed the command line using the command line described in:
"Run EGAPx for the first time to copy the config files so you can edit them:"

Now, I used the docker (adding "-e docker") and seems to be working .
