### ISSUE TITLE
Run set clean has multiple run ids in read files

### ISSUE THREAD

**Issue by bismarck1008** [ncbi/egapx#59]
python3 /data/bio-software/egapx/ui/egapx.py data/input_D_farinae_small.local4.yaml -e docker -o GCA_040085125.1_ASM4008512v1_4_out -w ./temp

!!WARNING!!
This is an alpha release with limited features and organism scope to collect initial feedback on execution. Outputs are not yet complete and not intended for production use.

Error: Run set clean has multiple run ids in read files: ['SRR16848208', 'SRR16848207', 'SRR16848205', 'SRR16848206']

**Comment by pstrope** [comment]
Can you post your yaml file?

**Comment by bismarck1008** [comment]
> Can you post your yaml file?

genome: /data/dell/CNI.2024.10.5/deer.ref/GCA_040085125.1_ASM4008512v1_genomic.fna
taxid: 1618199
reads:
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848205_R1.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848205_R2.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848206_R1.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848206_R2.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848207_R1.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848207_R2.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848208_R1.fq.gz
 - /data/dell/raw_data/2024.9.23_Deer/rna/PRJNA778640_trim/clean.SRR16848208_R2.fq.gz

**Comment by pstrope** [comment]
Looks like it is having trouble reading the files. 
Could you try this? Rename the files so that you remove the "." after clean:
clean.SRR16848208_R2.fq.gz -> cleanSRR16848208_R2.fq.gz

**Comment by bismarck1008** [comment]
> Looks like it is having trouble reading the files. Could you try this? Rename the files so that you remove the "." after clean: clean.SRR16848208_R2.fq.gz -> cleanSRR16848208_R2.fq.gz
It worked. But such yaml works, although it still aborts later
- /data/dell/CNI.2024.10.5/anotation/data/split.list00_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list00_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list01_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list01_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list02_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list02_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list03_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list03_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list04_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list04_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list05_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list05_R2.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list06_R1.fq.gz
 - /data/dell/CNI.2024.10.5/anotation/data/split.list06_R2.fq.gz

**Comment by pstrope** [comment]
When you get an error, please post here, that helps us. Thank you for testing!

**Comment by bismarck1008** [comment]
> When you get an error, please post here, that helps us. Thank you for testing!
Still reporting errors in the following step, possibly related to large data volume or data merging, as the running file has been deleted and details cannot be provided

process > egapx:rnaseq_short_plane:rnaseq_collapse:run_rnaseq_collapse

**Comment by pstrope** [comment]
Closing this ticket. Please open a new one if you come across any errors.
