### ISSUE TITLE
egapx:annot_proc_plane:annot_builder:annot_builder_run:  error

### ISSUE THREAD

**Issue by bismarck1008** [ncbi/egapx#60]
[38/06631d] process > egapx:annot_proc_plane:annot_builder:annot_builder_run                                               [100%] 4 of 4, failed: 4, retries: 3 ✘

[79/9b8e63] NOTE: Process `egapx:annot_proc_plane:annot_builder:annot_builder_run` terminated with an error exit status (3) -- Execution is retried (1)
[cd/7f0c3a] NOTE: Process `egapx:annot_proc_plane:annot_builder:annot_builder_run` terminated with an error exit status (3) -- Execution is retried (2)
[a5/08981d] NOTE: Process `egapx:annot_proc_plane:annot_builder:annot_builder_run` terminated with an error exit status (3) -- Execution is retried (3)
ERROR ~ Error executing process > 'egapx:annot_proc_plane:annot_builder:annot_builder_run'

Caused by:
  Process `egapx:annot_proc_plane:annot_builder:annot_builder_run` terminated with an error exit status (3)

Command executed:

  mkdir -p outdir/ACCEPT
  mkdir -p outdir/COLLECTION
  mkdir -p outdir/CONFLICT
  mkdir -p outdir/REPORT
  mkdir -p outdir/TEST

  lds2_indexer -source genome/ -db LDS2
  # EXCEPTION_STACK_TRACE_LEVEL=Warning DEBUG_STACK_TRACE_LEVEL=Warning DIAG_POST_LEVEL=Trace
  annot_builder -accept-output both -nogenbank -lds2 LDS2 -conffile annot_builder_final.ini -gc-assembly gencoll.asn -logfile outdir/annot_builder.log
  cat outdir/ACCEPT/*.ftable.annot > outdir/ACCEPT/accept.ftable_annot

Command exit status:
  3

Command output:
  (empty)

Work dir:
  /data/dell/CNI.2024.10.5/2.anotation/temp/38/06631df7dbb3ee5b163f3cc40ed030

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '15.4_out/nextflow.log' file for details

**Comment by xuzhougeng** [comment]
same problem

**Comment by xuzhougeng** [comment]
@bismarck1008 you can check the naming of your genome, my problem was caused by all numbers, if you have all numbers too, try adding a character like chr before the number, it might solve the problem!

**Comment by bismarck1008** [comment]
Thank you very much. It worked.
