### ISSUE TITLE
Error egapx:rnaseq_short_plane:star:run_star

### ISSUE THREAD

**Issue by ElizabethBrooks** [ncbi/egapx#66]
The current version of EGAPx (v0.3.1) cannot complete the annotation process when isoseq data is included. Attached are the inputs and log files. The annotations were able to be created using these inputs with previous versions of EGAPx (v0.1 and v0.2). 

[D_pulex_KAP4_NCBI_medium.zip](https://github.com/user-attachments/files/18118052/D_pulex_KAP4_NCBI_medium.zip)

**Comment by murphyte** [comment]
EGAPx does not yet support IsoSeq data. We're starting to work on it now, but please stick to just short reads with the current version.

**Comment by ElizabethBrooks** [comment]
Ah, gotcha. We will just use the short read data with EGAPx for now. Thank you!

**Comment by ElizabethBrooks** [comment]
Ah, gotcha. We will just use the short read data with EGAPx for now. Thank you!
