### ISSUE TITLE
reads_ids and reads_query won't work for me

### ISSUE THREAD

**Issue by amcooksey** [ncbi/egapx#8]
When I run input_D_farinae_small_rnaseq.yaml it works great and finishes in about 20 min. 

When I try to run input_C_longicornis.yaml (with the reads_query option) it gets stuck in the STAR step and after about 3 hrs it aborts with this error: "Cause: Process `egapx:star:exec (1)` terminated with an error exit status (3)". 

I've also tried D farinae (and a couple other arthropod species) with the reads_ids option and a single SRA accession and I get the same error. 

One thing I have noticed is that when it succeeds (reads: option) it executes "egapx:star_simplified:exec (1)" and when it fails it is trying to execute "egapx:star:exec (1)". I'm not sure if that's the cause but it is consistently different.

**Comment by pstrope** [comment]
Hi, 
Are you running it on HPC or Cloud? Did you use singularity or docker?

We just pushed version 0.1.1 today with some bug fixes. If you could test that out and see if it works?

thanks,
Pooja

**Comment by amcooksey** [comment]
I'm using Singulairty on our HPC. I will pull the new version and try it out tomorrow.

Thanks.

**Comment by pstrope** [comment]
For slurm in your HPC, you will have to edit `egap_config/slurm.config` as per your cluster, and then use `-e slurm` option in the command line. 
Let us know, we'll work with you!

Pooja

**Comment by amcooksey** [comment]
I pulled the new version and I have things working now. I am running this on the USDA ceres system. I found a nextflow config file specific to ceres that seems to work here: https://github.com/nf-core/configs/blob/master/conf/ceres.config
(in case you find someone else using ceres).
Thanks for your help,
Amanda

**Comment by victzh** [comment]
Thanks, @amcooksey. There are other users indeed who use Ceres and I hope this will help them.
